"""added is_admin to user

Revision ID: 7d4fe50b4106
Revises: 261362dcee8c
Create Date: 2026-02-23 15:33:56.915548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4fe50b4106'
down_revision: Union[str, Sequence[str], None] = '261362dcee8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    import sqlmodel
    # add with a server default so existing rows get False
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='0'))

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
